# docker-compose.yml
version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: fastapi_app
    restart: always
    expose:
      - "8000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi
