version: '3.8'
services:
  app:
    build: ./app
    container_name: fastapi_app
    restart: always
    networks:
      - appnet

  nginx:
    image: nginx:stable-alpine
    container_name: fastapi_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"       # ローカルでは http://localhost:8000 で動作確認
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
